# Generated by Django 5.2.5 on 2025-10-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('movies', '0003_alter_movies_actors_alter_movies_directors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='movie',
        ),
        migrations.AddField(
            model_name='category',
            name='movies',
            field=models.ManyToManyField(related_name='categories', to='movies.movies'),
        ),
    ]
