# Generated by Django 5.2.5 on 2025-10-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_movie_category_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='movies',
        ),
    ]
