# Generated by Django 5.2.6 on 2025-10-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('categories', '0001_initial'),
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(related_name='movies', to='actors.actor')),
                ('categories', models.ManyToManyField(related_name='movies', to='categories.category')),
                ('directors', models.ManyToManyField(related_name='movies', to='directors.director')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
