# Generated by Django 5.2.6 on 2025-10-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='director',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='directors/'),
        ),
    ]
