# Generated by Django 5.2.5 on 2025-10-08 22:07

import directors.models
import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='imdb_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='director',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='director',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='director',
            name='profile_img',
            field=models.ImageField(blank=True, help_text='Allowed formats: JPG/PNG/WEBP, max size 3MB.', upload_to='directors/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), directors.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='director',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='director',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='director',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short biography of the director.'),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(help_text="Director's name (displayed publicly).", max_length=80, validators=[django.core.validators.RegexValidator(message='Name should not contain any digits.', regex='^[^\\d]+$')]),
        ),
        migrations.AddConstraint(
            model_name='director',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_director_name_ci', violation_error_message='A director with this name already exists (case-insensitive).'),
        ),
    ]
