# Generated by Django 5.2.5 on 2025-10-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='directors/'),
        ),
    ]
