# Generated by Django 5.2.5 on 2025-10-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0002_alter_director_options_director_date_of_birth_and_more'),
    ]

    operations = [
    ]
