# Generated by Django 5.2.5 on 2025-10-08 22:12

import directors.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0004_populate_slugs'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='director',
            name='uniq_director_name_ci',
        ),
        migrations.RemoveField(
            model_name='director',
            name='slug',
        ),
        migrations.AlterField(
            model_name='director',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short biography.'),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(help_text="Director's name (public).", max_length=80, validators=[django.core.validators.RegexValidator(message='Name should not contain digits.', regex='^[^\\d]+$')]),
        ),
        migrations.AlterField(
            model_name='director',
            name='profile_img',
            field=models.ImageField(blank=True, help_text='JPG/PNG/WEBP ≤ 3MB', upload_to='directors/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), directors.models.validate_image_size]),
        ),
    ]
