# Generated by Django 5.2.5 on 2025-10-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group_project_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='category',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.DeleteModel(
            name='Actors',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Directors',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
