# Generated by Django 5.2.5 on 2025-10-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('directors', '0001_initial'),
        ('movies', '0002_alter_movies_actors_alter_movies_directors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='actors.actor'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='directors',
            field=models.ManyToManyField(related_name='movies', to='directors.director'),
        ),
    ]
