# Generated by Django 5.2.5 on 2025-10-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_movies'),
        ('movies', '0003_alter_movies_actors_alter_movies_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='categories',
            field=models.ManyToManyField(related_name='movies', to='categories.category'),
        ),
    ]
