# Generated by Django 5.2.5 on 2025-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
