# Generated by Django 5.2.5 on 2025-10-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movies_imdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='imdb_id',
        ),
    ]
